2023-07-17 11:14:15,419 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-07-17 11:14:15,884 django.request WARNING  Not Found: /static/media/logo.png
2023-08-24 12:26:24,810 django.request WARNING  Not Found: /index.html
2023-08-24 12:26:30,427 django.request WARNING  Not Found: /index.html
2023-08-24 12:26:55,379 django.request WARNING  Not Found: /favicon.ico
2023-08-24 13:19:24,654 django.request ERROR    Internal Server Error: /schema/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  [Previous line repeated 6 more times]
  File "/usr/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SerializerMetaclass is not JSON serializable
2023-08-24 13:19:24,867 django.request ERROR    Internal Server Error: /schema/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  [Previous line repeated 6 more times]
  File "/usr/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SerializerMetaclass is not JSON serializable
2023-08-24 13:20:09,877 django.request ERROR    Internal Server Error: /schema/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  [Previous line repeated 6 more times]
  File "/usr/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SerializerMetaclass is not JSON serializable
2023-08-24 13:20:10,040 django.request ERROR    Internal Server Error: /schema/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 202, in encode
    chunks = list(chunks)
             ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  [Previous line repeated 6 more times]
  File "/usr/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SerializerMetaclass is not JSON serializable
2023-08-24 13:26:17,404 django.request ERROR    Internal Server Error: /schema/
2023-08-24 13:26:17,520 django.request ERROR    Internal Server Error: /schema/
2023-08-24 13:26:58,563 django.request ERROR    Internal Server Error: /schema/
2023-08-24 13:26:58,620 django.request ERROR    Internal Server Error: /schema/
2023-08-24 13:35:58,441 django.request ERROR    Internal Server Error: /schema/
2023-08-24 13:35:58,548 django.request ERROR    Internal Server Error: /schema/
2023-08-24 17:40:22,874 cities_light INFO     Creating /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data
2023-08-24 17:40:28,924 cities_light INFO     Downloading http://download.geonames.org/export/dump/countryInfo.txt into /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/countryInfo.txt
2023-08-24 17:40:29,615 cities_light INFO     Forced import of countryInfo.txt because data do not seem to have installed successfuly yet, note that this is equivalent to --force-import-all.
2023-08-24 17:40:29,615 cities_light INFO     Importing countryInfo.txt
2023-08-24 17:40:33,432 cities_light INFO     Downloading http://download.geonames.org/export/dump/admin1CodesASCII.txt into /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/admin1CodesASCII.txt
2023-08-24 17:40:34,951 cities_light INFO     Forced import of admin1CodesASCII.txt because data do not seem to have installed successfuly yet, note that this is equivalent to --force-import-all.
2023-08-24 17:40:34,952 cities_light INFO     Importing admin1CodesASCII.txt
2023-08-24 17:41:29,164 cities_light INFO     Downloading http://download.geonames.org/export/dump/admin2Codes.txt into /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/admin2Codes.txt
2023-08-24 17:41:34,435 cities_light INFO     Forced import of admin2Codes.txt because data do not seem to have installed successfuly yet, note that this is equivalent to --force-import-all.
2023-08-24 17:41:34,435 cities_light INFO     Importing admin2Codes.txt
2023-08-24 17:46:15,390 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:46:15,578 django.request WARNING  Not Found: /static/media/logo.png
2023-08-24 17:46:20,328 django.request ERROR    Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column accounts_user.dob does not exist
LINE 1: ...ts_user"."country_id", "accounts_user"."city_id", "accounts_...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/generic/edit.py", line 152, in post
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/forms.py", line 201, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/forms.py", line 196, in errors
    self.full_clean()
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/forms.py", line 434, in full_clean
    self._clean_form()
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/forms.py", line 455, in _clean_form
    cleaned_data = self.clean()
                   ^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/forms.py", line 242, in clean
    self.user_cache = authenticate(
                      ^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/base_user.py", line 54, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column accounts_user.dob does not exist
LINE 1: ...ts_user"."country_id", "accounts_user"."city_id", "accounts_...
                                                             ^
2023-08-24 17:46:20,562 django.request WARNING  Not Found: /favicon.ico
2023-08-24 17:46:44,995 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:46:45,129 django.request WARNING  Not Found: /static/media/logo.png
2023-08-24 17:46:51,331 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:46:58,045 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:50:40,512 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:50:40,515 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:50:40,779 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:50:43,801 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:50:43,803 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:50:44,486 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:50:45,254 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:50:59,229 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:50:59,231 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:50:59,473 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:50:59,761 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:51:05,846 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:51:05,849 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:51:06,082 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:51:06,242 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:51:59,462 cities_light WARNING  Assuming local download is up to date for http://download.geonames.org/export/dump/countryInfo.txt
2023-08-24 17:51:59,462 cities_light INFO     Forced import of countryInfo.txt because data do not seem to have installed successfuly yet, note that this is equivalent to --force-import-all.
2023-08-24 17:51:59,462 cities_light INFO     Importing countryInfo.txt
2023-08-24 17:52:03,319 cities_light WARNING  Assuming local download is up to date for http://download.geonames.org/export/dump/admin1CodesASCII.txt
2023-08-24 17:52:03,319 cities_light INFO     Forced import of admin1CodesASCII.txt because data do not seem to have installed successfuly yet, note that this is equivalent to --force-import-all.
2023-08-24 17:52:03,320 cities_light INFO     Importing admin1CodesASCII.txt
2023-08-24 17:52:08,258 cities_light WARNING  Assuming local download is up to date for http://download.geonames.org/export/dump/admin2Codes.txt
2023-08-24 17:52:08,258 cities_light INFO     Forced import of admin2Codes.txt because data do not seem to have installed successfuly yet, note that this is equivalent to --force-import-all.
2023-08-24 17:52:08,258 cities_light INFO     Importing admin2Codes.txt
2023-08-24 17:54:47,662 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:54:47,665 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:54:47,858 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:54:47,965 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:54:48,556 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:54:48,558 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:54:48,761 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:54:48,877 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:54:48,926 django.request WARNING  Not Found: /static/media/logo.png
2023-08-24 17:55:24,736 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:55:24,738 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:55:25,179 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:55:25,314 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:55:32,062 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:55:32,064 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:55:32,239 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:55:32,399 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:55:32,455 django.request WARNING  Not Found: /static/media/logo.png
2023-08-24 17:55:36,045 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:55:36,047 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:55:36,319 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:55:36,567 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:55:39,295 cities_light INFO     Downloading http://download.geonames.org/export/dump/cities15000.zip into /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/cities15000.zip
2023-08-24 17:55:45,278 cities_light INFO     Extracting cities15000.txt from /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/cities15000.zip into /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/cities15000.txt
2023-08-24 17:55:45,343 cities_light INFO     Forced import of cities15000.zip because data do not seem to have installed successfuly yet, note that this is equivalent to --force-import-all.
2023-08-24 17:55:45,343 cities_light INFO     Importing cities15000.zip
2023-08-24 17:56:35,567 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:56:35,571 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:56:35,992 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:56:36,123 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:56:41,932 cities_light WARNING  Saving Zhonghe, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Zhonghe) already exists.')
2023-08-24 17:56:44,432 cities_light WARNING  Saving Xinglong, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Xinglong) already exists.')
2023-08-24 17:56:50,485 cities_light WARNING  Saving Longtan, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Longtan) already exists.')
2023-08-24 17:56:50,985 cities_light WARNING  Saving Linjiang, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Linjiang) already exists.')
2023-08-24 17:56:54,386 cities_light WARNING  Saving Guandu, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Guandu) already exists.')
2023-08-24 17:56:57,587 cities_light WARNING  Saving Longxing, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Longxing) already exists.')
2023-08-24 17:56:58,497 cities_light WARNING  Saving Shuanglong, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Shuanglong) already exists.')
2023-08-24 17:56:59,608 cities_light WARNING  Saving Sanjiao, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Sanjiao) already exists.')
2023-08-24 17:57:00,052 cities_light WARNING  Saving Shima, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Shima) already exists.')
2023-08-24 17:57:00,284 cities_light WARNING  Saving Taiping, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Taiping) already exists.')
2023-08-24 17:57:03,472 cities_light WARNING  Saving E’zhou, Hubei, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_slug_efb2e768_uniq"\nDETAIL:  Key (region_id, subregion_id, slug)=(627, 9789, ezhou) already exists.')
2023-08-24 17:57:04,662 cities_light WARNING  Saving Wushan, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Wushan) already exists.')
2023-08-24 17:57:04,687 cities_light WARNING  Saving Zhuxi, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Zhuxi) already exists.')
2023-08-24 17:57:05,017 cities_light WARNING  Saving Tai’an, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Tai’an) already exists.')
2023-08-24 17:57:05,172 cities_light WARNING  Saving Xinmin, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Xinmin) already exists.')
2023-08-24 17:57:05,197 cities_light WARNING  Saving Yong’an, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Yong’an) already exists.')
2023-08-24 17:57:05,230 cities_light WARNING  Saving Gaofeng, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Gaofeng) already exists.')
2023-08-24 17:57:05,372 cities_light WARNING  Saving Xinsheng, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Xinsheng) already exists.')
2023-08-24 17:57:05,562 cities_light WARNING  Saving Tonggu, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Tonggu) already exists.')
2023-08-24 17:57:05,629 cities_light WARNING  Saving Sanhe, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Sanhe) already exists.')
2023-08-24 17:57:05,635 cities_light WARNING  Saving Xintian, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Xintian) already exists.')
2023-08-24 17:57:05,816 cities_light WARNING  Saving Yihe, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Yihe) already exists.')
2023-08-24 17:57:05,972 cities_light WARNING  Saving Longhe, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Longhe) already exists.')
2023-08-24 17:57:06,074 cities_light WARNING  Saving Gulu, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Gulu) already exists.')
2023-08-24 17:57:06,360 cities_light WARNING  Saving Longfeng, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Longfeng) already exists.')
2023-08-24 17:57:06,366 cities_light WARNING  Saving Longxing, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Longxing) already exists.')
2023-08-24 17:57:08,305 cities_light WARNING  Saving Shizuishan, Ningxia Hui Autonomous Region, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(623, 9697, Shizuishan) already exists.')
2023-08-24 17:57:09,596 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:57:09,598 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:57:09,684 cities_light WARNING  Saving Liangping, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Liangping) already exists.')
2023-08-24 17:57:09,689 cities_light WARNING  Saving Xinglong, Chongqing, China failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(636, 9924, Xinglong) already exists.')
2023-08-24 17:57:10,061 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:10,226 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:14,273 cities_light WARNING  Saving Buenaventura, Valle del Cauca, Colombia failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(645, 10949, Buenaventura) already exists.')
2023-08-24 17:57:14,682 cities_light WARNING  Saving Bosconia, Cesar, Colombia failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(664, 10906, Bosconia) already exists.')
2023-08-24 17:57:15,017 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:57:15,020 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:57:15,420 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:15,541 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:18,397 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:57:18,399 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:57:18,842 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:18,980 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:28,774 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:57:28,776 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:57:29,212 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:29,315 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:31,096 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:57:31,099 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:57:31,546 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:32,783 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:57:32,785 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:57:33,199 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:33,334 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:34,429 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:57:34,434 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:57:34,948 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:35,107 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:57:35,947 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:57:35,950 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:57:36,444 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:58:13,404 cities_light WARNING  Saving Hayes, England, United Kingdom failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(1028, 13468, Hayes) already exists.')
2023-08-24 17:59:50,566 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 17:59:50,569 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 17:59:51,020 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 17:59:51,202 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:00:21,591 cities_light WARNING  Saving Panauti, Bagmati Province, Nepal failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_slug_efb2e768_uniq"\nDETAIL:  Key (region_id, subregion_id, slug)=(2414, 27928, panauti) already exists.')
2023-08-24 18:00:31,558 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:00:31,560 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:00:32,015 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:00:32,168 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:01:01,831 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:01:01,834 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:01:02,321 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:01:02,471 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:01:54,208 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:01:54,211 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:01:54,663 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:01:54,804 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:02:10,337 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:02:10,339 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:02:10,775 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:02:14,320 cities_light WARNING  Saving Vincent, California, United States failed: IntegrityError('duplicate key value violates unique constraint "cities_light_city_region_id_subregion_id_name_cdfc77ea_uniq"\nDETAIL:  Key (region_id, subregion_id, name)=(3637, 42269, Vincent) already exists.')
2023-08-24 18:02:31,655 cities_light INFO     Downloading http://download.geonames.org/export/dump/alternateNames.zip into /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/alternateNames.zip
2023-08-24 18:02:48,830 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:02:48,832 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:02:49,259 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:01,436 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:03:01,438 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:03:01,911 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:02,015 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:06,277 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:03:06,280 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:03:06,666 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:06,780 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:08,605 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:03:08,608 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:03:09,036 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:09,140 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:21,064 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:03:21,067 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:03:22,524 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:23,195 django.request WARNING  Not Found: /static/media/logo.png
2023-08-24 18:03:38,889 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:03:38,891 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:03:39,491 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:52,097 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:03:52,099 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:03:52,719 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:03:52,868 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:05:56,995 cities_light INFO     Extracting alternateNames.txt from /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/alternateNames.zip into /home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/cities_light/data/alternateNames.txt
2023-08-24 18:06:01,020 cities_light INFO     Forced import of alternateNames.zip because data do not seem to have installed successfuly yet, note that this is equivalent to --force-import-all.
2023-08-24 18:06:01,020 cities_light INFO     Importing alternateNames.zip
2023-08-24 18:07:01,607 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:07:01,610 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:07:02,257 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:07:02,412 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:07:07,133 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:07:07,135 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:07:07,693 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:07:07,870 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:27:59,021 django.request ERROR    Internal Server Error: /api/v1/auth/register/
2023-08-24 18:30:11,925 django.request ERROR    Internal Server Error: /api/v1/auth/register/
2023-08-24 18:33:14,109 django.request ERROR    Internal Server Error: /api/v1/auth/register/
2023-08-24 18:33:16,266 django.request ERROR    Internal Server Error: /api/v1/auth/register/
2023-08-24 18:34:01,021 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-24 18:34:06,579 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-24 18:34:33,853 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:34:33,856 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:34:34,119 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:34:34,323 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:34:34,419 django.request WARNING  Not Found: /static/media/logo.png
2023-08-24 18:34:42,033 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:34:42,037 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:34:42,334 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:34:42,495 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:34:44,286 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:34:44,289 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:34:44,570 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:37:22,894 django.request ERROR    Internal Server Error: /api/v1/auth/register/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/adrf/views.py", line 60, in async_dispatch
    response = await handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/apps/accounts/views.py", line 51, in post
    await Util.send_activation_otp(user)
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/apps/accounts/emails.py", line 27, in send_activation_otp
    otp = await accounts_models.Otp.objects.get_or_none(user=user)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/apps/common/managers.py", line 27, in get_or_none
    return self.get_queryset().get_or_none(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/apps/common/managers.py", line 9, in get_or_none
    return self.get(**kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/asyncio.py", line 24, in inner
    raise SynchronousOnlyOperation(message)
django.core.exceptions.SynchronousOnlyOperation: You cannot call this from an async context - use a thread or sync_to_async.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/adrf/views.py", line 63, in async_dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/rest_framework/views.py", line 466, in handle_exception
    response = exception_handler(exc, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/apps/common/exceptions.py", line 56, in custom_exception_handler
    status=response.status_code,
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
2023-08-24 18:37:59,649 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:37:59,652 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:37:59,868 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:38:00,022 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:38:05,888 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:38:05,891 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:38:06,121 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:38:08,200 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:38:08,202 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:38:08,413 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:38:08,518 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:38:15,553 django.request ERROR    Internal Server Error: /api/v1/auth/register/
2023-08-24 18:40:54,969 django.request ERROR    Internal Server Error: /api/v1/auth/register/
2023-08-24 18:42:06,082 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-24 18:42:08,592 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-24 18:42:13,731 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:42:13,734 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:42:13,944 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:42:14,160 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:42:18,446 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:42:18,450 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:42:18,588 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:42:18,735 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:42:20,371 jazzmin.utils WARNING  listings not found when generating links
2023-08-24 18:42:20,373 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-24 18:42:20,580 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:42:20,706 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-24 18:45:07,150 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-24 18:46:57,859 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-24 18:56:41,008 django.request ERROR    Internal Server Error: /schema/
2023-08-24 18:56:41,089 django.request ERROR    Internal Server Error: /schema/
2023-08-24 19:21:26,814 django.request WARNING  Not Found: /api/v1/auth/resend-verification-email/
2023-08-24 19:22:15,807 django.request WARNING  Not Found: /api/v1/auth/verify-email/
2023-08-24 19:22:23,477 django.request WARNING  Not Found: /api/v1/auth/verify-email/
2023-08-24 19:22:57,736 django.request WARNING  Not Found: /api/v1/auth/send-password-reset-otp/
2023-08-24 19:23:30,980 django.request WARNING  Unprocessable Entity: /api/v1/auth/set-new-password/
2023-08-24 19:28:50,159 django.request WARNING  Unprocessable Entity: /api/v1/auth/set-new-password/
2023-08-24 19:28:58,091 django.request WARNING  Unprocessable Entity: /api/v1/auth/set-new-password/
2023-08-24 19:29:05,679 django.request WARNING  Not Found: /api/v1/auth/set-new-password/
2023-08-24 19:29:17,233 django.request WARNING  Not Found: /api/v1/auth/set-new-password/
2023-08-25 18:15:27,849 django.request WARNING  Not Found: /api/v4/auth/send-password-reset-otp/
2023-08-25 18:16:54,211 django.request WARNING  Not Found: /api/v1/auth/send-password-reset-otp/
2023-08-25 18:16:55,289 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-25 18:16:56,052 django.request WARNING  Not Found: /api/v1/auth/resend-verification-email/
2023-08-25 18:20:13,298 django.request WARNING  Not Found: /api/v1/auth/send-password-reset-otp/
2023-08-25 18:20:14,401 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-25 18:20:15,124 django.request WARNING  Not Found: /api/v1/auth/resend-verification-email/
2023-08-25 18:20:15,844 django.request WARNING  Not Found: /api/v1/auth/set-new-password/
2023-08-25 18:20:15,851 django.request WARNING  Not Found: /api/v1/auth/set-new-password/
2023-08-25 18:20:16,917 django.request WARNING  Not Found: /api/v1/auth/verify-email/
2023-08-25 18:36:36,613 django.request WARNING  Not Found: /api/v1/auth/send-password-reset-otp/
2023-08-25 18:36:37,352 django.request WARNING  Unauthorized: /api/v1/auth/login/
2023-08-25 18:36:37,719 django.request WARNING  Unauthorized: /api/v1/auth/login/
2023-08-25 18:36:38,798 django.request WARNING  Unauthorized: /api/v1/auth/logout/
2023-08-25 18:36:39,601 django.request WARNING  Not Found: /api/v1/auth/refresh/
2023-08-25 18:36:39,605 django.request WARNING  Unauthorized: /api/v1/auth/refresh/
2023-08-25 18:36:40,686 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-25 18:36:41,459 django.request WARNING  Not Found: /api/v1/auth/resend-verification-email/
2023-08-25 18:36:42,206 django.request WARNING  Not Found: /api/v1/auth/set-new-password/
2023-08-25 18:36:42,212 django.request WARNING  Not Found: /api/v1/auth/set-new-password/
2023-08-25 18:36:43,294 django.request WARNING  Not Found: /api/v1/auth/verify-email/
2023-08-25 18:42:19,939 django.request WARNING  Unauthorized: /api/v1/auth/login/
2023-08-25 18:42:35,633 django.request WARNING  Unauthorized: /api/v1/auth/login/
2023-08-25 18:45:19,835 django.request WARNING  Not Found: /api/v1/auth/refresh/
2023-08-25 18:46:02,731 django.request WARNING  Unauthorized: /api/v1/auth/logout/
2023-08-25 18:46:15,856 django.request WARNING  Unauthorized: /api/v1/auth/logout/
2023-08-25 18:46:32,206 django.request WARNING  Not Found: /api/v1/auth/send-password-reset-otp/
2023-08-25 18:46:33,104 django.request WARNING  Unauthorized: /api/v1/auth/login/
2023-08-25 18:46:33,617 django.request WARNING  Unauthorized: /api/v1/auth/login/
2023-08-25 18:46:34,940 django.request WARNING  Unauthorized: /api/v1/auth/logout/
2023-08-25 18:46:35,768 django.request WARNING  Not Found: /api/v1/auth/refresh/
2023-08-25 18:46:35,773 django.request WARNING  Unauthorized: /api/v1/auth/refresh/
2023-08-25 18:46:37,246 django.request WARNING  Unprocessable Entity: /api/v1/auth/register/
2023-08-25 18:46:38,271 django.request WARNING  Not Found: /api/v1/auth/resend-verification-email/
2023-08-25 18:46:39,072 django.request WARNING  Not Found: /api/v1/auth/set-new-password/
2023-08-25 18:46:39,078 django.request WARNING  Not Found: /api/v1/auth/set-new-password/
2023-08-25 18:46:40,325 django.request WARNING  Not Found: /api/v1/auth/verify-email/
2023-08-26 00:25:53,691 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:25:53,975 django.request WARNING  Not Found: /static/media/logo.png
2023-08-26 00:25:58,303 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:25:58,307 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:25:58,617 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:31:30,889 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:31:30,894 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:31:31,035 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:31:33,895 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:31:33,898 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:31:34,222 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:31:35,945 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:31:35,947 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:31:36,185 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:31:36,307 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:32:19,836 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:32:19,840 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:32:20,109 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:33:13,843 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:33:13,845 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:33:14,124 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:33:14,277 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:33:19,325 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:33:19,327 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:33:19,673 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:33:37,842 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:33:37,845 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:33:38,122 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:33:38,276 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:33:40,562 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:33:40,564 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:35:05,646 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:35:05,648 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:35:05,932 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:35:27,565 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:35:27,567 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:35:27,833 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:35:30,421 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:35:30,423 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:35:32,721 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:35:32,725 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:35:33,062 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:35:33,223 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:35:41,982 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 00:35:41,984 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 00:35:42,214 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 00:35:42,407 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:38:22,611 django.request ERROR    Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedColumn: column accounts_user.username does not exist
LINE 1: ..._user"."first_name", "accounts_user"."last_name", "accounts_...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 230, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/functional.py", line 266, in inner
    self._setup()
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 161, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: column accounts_user.username does not exist
LINE 1: ..._user"."first_name", "accounts_user"."last_name", "accounts_...
                                                             ^
2023-08-26 15:38:33,342 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:38:33,345 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:38:33,588 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:38:36,755 django.request ERROR    Internal Server Error: /admin/accounts/user/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/views/main.py", line 122, in __init__
    self.queryset = self.get_queryset(request)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/views/main.py", line 503, in get_queryset
    ) = self.get_filters(request)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/views/main.py", line 180, in get_filters
    field = get_fields_from_path(self.model, field_path)[-1]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/utils.py", line 517, in get_fields_from_path
    fields.append(parent._meta.get_field(piece))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/db/models/options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: User has no field named 'username'
2023-08-26 15:38:51,040 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:38:51,043 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:38:51,302 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:38:51,565 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:38:57,152 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:38:57,154 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:38:57,381 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:38:57,528 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:38:59,258 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:38:59,261 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:38:59,506 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:38:59,633 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:39:37,296 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:39:37,298 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:39:37,546 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:39:42,098 django.request ERROR    Internal Server Error: /admin/accounts/user/d0626744-7c76-4ea4-b637-663c03c18fbf/change/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 300, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 198, in fields_for_model
    raise FieldError(
django.core.exceptions.FieldError: 'username' cannot be specified for User model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
                ^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/admin.py", line 98, in get_form
    return super().get_form(request, obj, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: 'username' cannot be specified for User model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class UserAdmin.
2023-08-26 15:43:09,165 django.request ERROR    Internal Server Error: /admin/accounts/user/d0626744-7c76-4ea4-b637-663c03c18fbf/change/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 300, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 198, in fields_for_model
    raise FieldError(
django.core.exceptions.FieldError: 'username' cannot be specified for User model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
                ^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/admin.py", line 98, in get_form
    return super().get_form(request, obj, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: 'username' cannot be specified for User model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class UserAdmin.
2023-08-26 15:43:39,783 django.request ERROR    Internal Server Error: /admin/accounts/user/d0626744-7c76-4ea4-b637-663c03c18fbf/change/
Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 809, in get_form
    return modelform_factory(self.model, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 642, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 300, in __new__
    fields = fields_for_model(
             ^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/forms/models.py", line 198, in fields_for_model
    raise FieldError(
django.core.exceptions.FieldError: 'username' cannot be specified for User model form as it is a non-editable field

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 534, in thread_handler
    raise exc_info[1]
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/current_thread_executor.py", line 40, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/asgiref/sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1889, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1782, in _changeform_view
    ModelForm = self.get_form(
                ^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/auth/admin.py", line 98, in get_form
    return super().get_form(request, obj, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kayprogrammer/Documents/Projects/Django/socialnet-v1/env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 811, in get_form
    raise FieldError(
django.core.exceptions.FieldError: 'username' cannot be specified for User model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class UserAdmin.
2023-08-26 15:45:56,055 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:45:56,058 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:46:01,076 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:47:31,485 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:47:31,487 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:47:34,038 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:47:42,815 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:47:42,817 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:47:45,589 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:47:45,776 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:48:50,360 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:48:50,364 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:48:52,786 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:48:52,850 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:48:59,920 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:48:59,922 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:49:00,137 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:00,274 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:02,540 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:49:02,545 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:49:02,873 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:02,987 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:18,896 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:49:18,898 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:49:19,175 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:37,904 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:49:37,906 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:49:38,152 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:38,286 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:49,165 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:49:49,167 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:49:49,380 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:49,502 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:49:58,242 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:49:58,244 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:49:58,369 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:50:02,464 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:50:02,467 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:50:02,702 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:50:02,841 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:50:10,249 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:50:10,253 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:50:10,871 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:50:10,945 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:50:11,254 django.request WARNING  Not Found: /static/media/logo.png
2023-08-26 15:50:42,484 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:50:42,488 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:50:42,700 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:50:42,851 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:50:44,417 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:50:44,420 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:50:44,680 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:51:17,900 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:51:17,905 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:51:20,376 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:51:31,851 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:51:31,855 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:51:31,983 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:51:32,982 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:51:32,984 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:51:33,231 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:51:33,319 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:51:35,871 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:51:35,873 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:51:36,096 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:51:36,218 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:51:55,833 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:51:55,835 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:51:58,292 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:51:58,383 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:53:09,390 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:53:09,393 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:53:09,634 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:53:11,865 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:53:11,867 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:53:12,031 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:53:12,181 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:53:12,247 django.request WARNING  Not Found: /static/media/logo.png
2023-08-26 15:53:19,405 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:53:19,408 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:53:19,715 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:53:26,308 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 15:53:26,310 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 15:53:26,558 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 15:53:26,673 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 16:05:19,212 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 16:06:56,939 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 16:07:53,306 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 17:34:54,814 django.request WARNING  Not Found: /api/v1/feed/posts/sdsdsd/
2023-08-26 17:35:22,832 django.request ERROR    Internal Server Error: /api/v1/feed/posts/test-admin-1c25cd81-aa6e-438d-b61c-556970f3e90a/
2023-08-26 17:39:35,169 django.request ERROR    Internal Server Error: /api/v1/feed/posts/test-admin-1c25cd81-aa6e-438d-b61c-556970f3e90a/
2023-08-26 17:39:51,131 django.request ERROR    Internal Server Error: /api/v1/feed/posts/test-admin-1c25cd81-aa6e-438d-b61c-556970f3e90a/
2023-08-26 17:41:51,314 django.request ERROR    Internal Server Error: /api/v1/feed/posts/test-admin-1c25cd81-aa6e-438d-b61c-556970f3e90a/
                                                                                                                                           2023-08-26 19:40:18,057 django.request WARNING  Unauthorized: /api/v1/feed/posts/
2023-08-26 19:40:25,837 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:40:42,895 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:42:13,264 django.request WARNING  Unauthorized: /api/v1/feed/posts/
2023-08-26 19:42:56,920 django.request WARNING  Unauthorized: /api/v1/feed/posts/
2023-08-26 19:43:07,451 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:43:26,171 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:45:28,669 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:46:18,492 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:49:14,172 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:49:55,621 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:51:10,588 django.request ERROR    Internal Server Error: /api/v1/feed/posts/
2023-08-26 19:59:15,505 django.request WARNING  Unprocessable Entity: /api/v1/feed/posts/
2023-08-26 19:59:20,913 django.request WARNING  Unprocessable Entity: /api/v1/feed/posts/
2023-08-26 20:09:33,485 django.request ERROR    Internal Server Error: /schema/
2023-08-26 20:09:33,557 django.request ERROR    Internal Server Error: /schema/
2023-08-26 21:41:31,323 jazzmin.utils WARNING  listings not found when generating links
2023-08-26 21:41:31,326 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-26 21:41:31,792 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-26 21:41:32,367 django.request WARNING  Not Found: /static/media/logo.png
2023-08-27 12:59:46,471 django.request WARNING  Unauthorized: /api/v1/feed/posts/
2023-08-27 13:08:51,042 django.request ERROR    Internal Server Error: /api/v1/feed/posts/aaa/
2023-08-27 13:09:14,647 django.request WARNING  Not Found: /api/v1/feed/posts/aaa/
2023-08-27 13:09:15,690 django.request WARNING  Not Found: /api/v1/feed/posts/aaa/
2023-08-27 13:09:16,568 django.request WARNING  Not Found: /api/v1/feed/posts/aaa/
2023-08-27 13:20:11,847 jazzmin.utils WARNING  listings not found when generating links
2023-08-27 13:20:11,851 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-27 13:20:12,354 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:20:12,823 django.request WARNING  Not Found: /static/media/logo.png
2023-08-27 13:20:40,845 django.request WARNING  Unauthorized: /api/v1/auth/login/
2023-08-27 13:20:46,561 jazzmin.utils WARNING  listings not found when generating links
2023-08-27 13:20:46,564 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-27 13:20:46,890 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:20:47,654 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:20:47,724 django.request WARNING  Not Found: /static/media/logo.png
2023-08-27 13:20:50,691 jazzmin.utils WARNING  listings not found when generating links
2023-08-27 13:20:50,693 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-27 13:20:51,468 jazzmin.utils WARNING  listings not found when generating links
2023-08-27 13:20:51,471 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-27 13:20:57,103 jazzmin.utils WARNING  listings not found when generating links
2023-08-27 13:20:57,112 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-27 13:21:00,473 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:21:00,653 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:21:00,768 django.request WARNING  Not Found: /static/media/logo.png
2023-08-27 13:21:10,522 jazzmin.utils WARNING  listings not found when generating links
2023-08-27 13:21:10,524 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-27 13:21:10,816 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:21:10,944 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:22:57,617 django.request WARNING  Bad Request: /api/v1/feed/posts/test-admin-25f27e39-8291-4803-8a58-38a234feab3e/
2023-08-27 13:23:01,650 django.request WARNING  Bad Request: /api/v1/feed/posts/test-admin-25f27e39-8291-4803-8a58-38a234feab3e/
2023-08-27 13:23:52,461 django.request WARNING  Bad Request: /api/v1/feed/posts/test-admin-25f27e39-8291-4803-8a58-38a234feab3e/
2023-08-27 13:24:29,561 django.request WARNING  Bad Request: /api/v1/feed/posts/test-admin-25f27e39-8291-4803-8a58-38a234feab3e/
2023-08-27 13:26:17,844 django.request WARNING  Bad Request: /api/v1/feed/posts/test-admin-25f27e39-8291-4803-8a58-38a234feab3e/
2023-08-27 13:26:49,923 jazzmin.utils WARNING  listings not found when generating links
2023-08-27 13:26:49,926 jazzmin.templatetags.jazzmin WARNING  avatar field must be an ImageField/URLField on the user model, or a callable
2023-08-27 13:26:50,211 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:26:50,383 django.request WARNING  Not Found: /static/media/banner2-icon3.png
2023-08-27 13:27:11,123 django.request WARNING  Unprocessable Entity: /api/v1/feed/posts/kenechi-ifeanyi-86bdd7fd-0d0e-42d5-82f8-8c622e2460/
2023-08-27 13:31:21,347 django.request ERROR    Internal Server Error: /api/v1/feed/posts/kenechi-ifeanyi-86bdd7fd-0d0e-42d5-82f8-8c622e2460/
2023-08-27 13:31:47,600 django.request WARNING  Not Found: /api/v1/feed/posts/kenechi-ifeanyi-86bdd7fd-0d0e-42d5-82f8-8c622e2460/
2023-08-28 01:00:10,504 django.request ERROR    Internal Server Error: /api/v1/feed/posts/test-admin-320febbb-0d28-4500-8f61-0319ffd53994/
2023-08-28 01:01:26,004 django.request WARNING  Unprocessable Entity: /api/v1/feed/posts/
2023-08-28 01:12:19,657 django.request WARNING  Not Found: /index.html
2023-08-28 01:12:31,714 django.request WARNING  Not Found: /favicon.ico
